
matrix:
  include:
    -
      # NodeJS Setup
      language: node_js
      node_js:
        - node

      cache:
        yarn: true

      script:
        - yarn install
        - yarn lint
        - yarn build

      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GIT_TOKEN
        keep-history: true
        fqdn: cpp-tour.com
        local-dir: dist
        target-branch: gh-pages
        email: github@arvid.io
        name: Travis CI
        project-name: cpp-tour
        on:
          branch: master

    -
      os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: COMPILER='g++-7'

      install:
        - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
        - mkdir -p ${DEPS_DIR}
        - cd ${DEPS_DIR}
        - |
          if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
            CMAKE_URL="https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz"
            mkdir cmake
            travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
            export PATH=${DEPS_DIR}/cmake/bin:${PATH}
          elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
            which cmake || brew install cmake
          fi

      before_script:
        - export CXX=${COMPILER}
        - cmake --version
        - $CXX --version
        - cd ${TRAVIS_BUILD_DIR}
        - mkdir -p build
        - cd build
        - cmake .. -G"Unix Makefiles"

      script:
        - make -j4
        - ctest -V -j 2

